DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS essay;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username VARCHAR(10) NOT NULL,
    email VARCHAR(10) NOT NULL,
    pass VARCHAR(10) NOT NULL
);

CREATE TABLE essay (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userId INTEGER, 
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content TEXT NOT NULL,
    FOREIGN KEY (userId) REFERENCES user(id)
);
